name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Debug environment
      run: |
        node -v
        npm -v
        pwd
        ls -la
        ls -la src || true
        cat package.json

    - name: Run tests
      run: npm test

    - name: Run Hello World
      run: npm start
