name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  # keep this to match your branch protection rule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Debug environment
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Jest version (if installed):"
          npx jest --version || echo "jest not found"
          echo "Repo root listing:"
          ls -la
          echo "src listing:"
          ls -la src || true
          echo "tests listing:"
          ls -la tests || true
          echo "package.json:"
          cat package.json

      - name: Run tests
        run: npm test

      - name: Run Hello World
        run: npm start
